# bootstrap a uv virtual env
venv:
  uv venv

# grab and sync all the deps in the pyproject
sync-deps:
  uv sync

# run the Jupyter notebook
run:
  uv run --with jupyter jupyter lab

# format will format the py code using ruff
format:
  uv run ruff format ./

# WARNING: gets rid of checkpoints and existing notebook contents
clean-notebook:
  uv run --with jupyter jupyter nbconvert --clear-output --inplace moe-scaling-law.ipynb

# "EVERYTHING."
all: venv sync-deps run
